### ISSUE TITLE
The system cannot find the drive specified

### ISSUE THREAD

**Issue by meru-a** [bmrf/standalone_scripts#12]
Hi!

First of all, THANK YOU very much!!! Your .bat file helped me finally resolve the issue with Error 1603 that prevents Java installs.

This is not an issue ticket - but probably something you would like to know.

It seemed to me that the bat file was running in circles with `The system cannot find the drive specified` showing up from time to time. It worked great overall though, so maybe there is a nitpick that needs to be done :)

**Comment by vocatus** [comment]
Which script are you referring to?
