### ISSUE TITLE
Java Nuker Doesn't remove control panel icon x64/x32

### ISSUE THREAD

**Issue by 7JD-MW** [bmrf/standalone_scripts#14]
Java Nuker Misc cleanup to remove

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ControlPanel\NameSpace\{4299124F-F2C3-41b4-9C73-9236B2AD0E8F}

And 

HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\explorer\ControlPanelWOW64\NameSpace\{4299124F-F2C3-41b4-9C73-9236B2AD0E8F}

**Comment by vocatus** [comment]
Can you list the keys with included CLI syntax for deletion?

**Comment by vocatus** [comment]
Added keys to script
